import re
from tkinter import filedialog, messagebox


def get_statistics(text):
    """
    Returns text statistics.
    """

    text = text.strip()

    # Character count (excluding leading/trailing spaces)
    characters = len(text)

    # Word count
    words = text.split()
    word_count = len(words)

    # Sentence count
    sentences = re.split(r'[.!?]+', text)
    sentences = [s for s in sentences if s.strip()]
    sentence_count = len(sentences)

    # Unique words
    unique_words = len(set(word.lower() for word in words))

    # Estimated reading time (200 words/minute)
    reading_time = max(1, round(word_count / 200))

    return {
        "characters": characters,
        "words": word_count,
        "sentences": sentence_count,
        "unique_words": unique_words,
        "reading_time": reading_time
    }


def export_report(stats):
    """
    Save text statistics as a report.
    """

    file_path = filedialog.asksaveasfilename(
        title="Save Report",
        defaultextension=".txt",
        filetypes=[("Text Files", "*.txt")]
    )

    if not file_path:
        return

    report = f"""
==============================
 AI Grammar Checker Report
==============================

Characters     : {stats['characters']}
Words          : {stats['words']}
Sentences      : {stats['sentences']}
Unique Words   : {stats['unique_words']}
Reading Time   : {stats['reading_time']} minute(s)

==============================
Generated by AI Grammar Checker
==============================
"""

    try:
        with open(file_path, "w", encoding="utf-8") as file:
            file.write(report)

        messagebox.showinfo(
            "Success",
            "Report exported successfully!"
        )

    except Exception as e:
        messagebox.showerror(
            "Error",
            str(e)
        )